# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, default='images/account/default.png', upload_to='images/account')),
                ('Name', models.CharField(max_length=50)),
                ('Year_Of_Passing', models.DecimalField(decimal_places=0, max_digits=4)),
                ('Eats_Fish', models.BooleanField(default=True)),
                ('Eats_Chicken', models.BooleanField(default=True)),
                ('Eats_Mutton', models.BooleanField(default=True)),
                ('Eats_Egg', models.BooleanField(default=True)),
                ('Room_Number', models.CharField(max_length=4)),
                ('Morning_Presence', models.BooleanField(default=False)),
                ('Evening_Presence', models.BooleanField(default=False)),
                ('Presence_Date', models.DateField(null=True)),
                ('Department', models.CharField(choices=[('ME', 'Mechanical Engineering'), ('CSE', 'Computer Science'), ('EE', 'Electrical Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communications'), ('MME', 'MTech: Mechanical'), ('MCSE', 'MTech: Computer Science'), ('MIT', 'MTech: Information Technology'), ('MEE', 'MTech: Electrical Engineering'), ('MECE', 'MTech: Electronics and Communication')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
