# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='dp',
            field=models.ImageField(blank=True, default='/account/default.png', upload_to='images/account'),
        ),
    ]
