# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='Department',
            field=models.CharField(choices=[('ME', 'Mechanical Engineering'), ('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communications'), ('MCA', 'Master of Computer Application'), ('MME', 'MTech: Mechanical'), ('MCSE', 'MTech: Computer Science'), ('MIT', 'MTech: Information Technology'), ('MEE', 'MTech: Electrical Engineering'), ('MECE', 'MTech: Electronics and Communication')], max_length=40),
        ),
    ]
