# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 02:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180206_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
