# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180206_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='dp',
            field=models.URLField(default='media/account/default.png'),
        ),
    ]
