# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180225_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='dp',
            field=models.URLField(blank=True, default='/media/account/default.png'),
        ),
    ]
