# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180225_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='dp',
            field=models.BinaryField(blank=True),
        ),
    ]
