# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_boarder_current_boarder'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarder',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='boarder',
            name='Mobile_No',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
