# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('credit', models.FloatField(default=0.0)),
                ('debit', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.Boarder')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('name', models.CharField(choices=[('net', 'Net Committee'), ('library', 'Library Committee'), ('recreation', 'Recreation Committee'), ('canteen', 'Canteen Committee'), ('mess', 'Mess Committee'), ('sport', 'Sport Committee')], max_length=20, primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(blank=True, to='account.Boarder')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.Committee'),
        ),
    ]
