# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_of_passing', models.DecimalField(decimal_places=0, max_digits=4)),
                ('eats_fish', models.BooleanField(default=True)),
                ('eats_chicken', models.BooleanField(default=True)),
                ('eats_mutton', models.BooleanField(default=True)),
                ('eats_egg', models.BooleanField(default=True)),
                ('room_number', models.CharField(max_length=4)),
                ('boarder', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('ME', 'Mechanical Engineering'), ('CSE', 'Computer Science'), ('EE', 'Electrical Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communications'), ('MME', 'MTech: Mechanical'), ('MCSE', 'MTech: Computer Science'), ('MIT', 'MTech: Information Technology'), ('MEE', 'MTech: Electrical Engineering'), ('MECE', 'MTech: Electronics and Communication')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('half', models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='meal_date')),
                ('change_by', models.DateTimeField()),
                ('meal_dishes', models.CharField(blank=True, max_length=150)),
                ('has_fish', models.BooleanField(default=False)),
                ('has_chicken', models.BooleanField(default=False)),
                ('has_mutton', models.BooleanField(default=False)),
                ('has_egg', models.BooleanField(default=False)),
                ('extra_meals', models.DecimalField(decimal_places=0, default=4, max_digits=2)),
                ('extra_description', models.TextField(default='')),
                ('adjust_count', models.IntegerField(default=0)),
                ('boarder', models.ManyToManyField(blank=True, to='mess.Boarder')),
            ],
        ),
    ]
