# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('half', models.CharField(choices=[('1MO', 'Morning'), ('2EV', 'Evening')], max_length=12)),
                ('number', models.IntegerField(default=0)),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Boarder')),
            ],
        ),
        migrations.CreateModel(
            name='MealDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('half', models.CharField(blank=True, choices=[('1MO', 'Morning'), ('2EV', 'Evening')], max_length=12, unique_for_date='date')),
                ('has_fish', models.BooleanField(default=False)),
                ('has_chicken', models.BooleanField(default=False)),
                ('has_mutton', models.BooleanField(default=False)),
                ('has_egg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('name', models.ManyToManyField(blank=True, to='account.Boarder', unique_for_month='start', unique_for_year='start')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], max_length=12)),
                ('half', models.CharField(choices=[('1MO', 'Morning'), ('2EV', 'Evening')], max_length=12)),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Boarder')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('half', models.CharField(choices=[('1MO', 'Morning'), ('2EV', 'Evening')], max_length=12, unique_for_date='date')),
                ('extra_meals', models.DecimalField(decimal_places=0, default=4, max_digits=2)),
                ('adjust_count', models.IntegerField(default=0)),
                ('guest_meal', models.ManyToManyField(blank=True, to='mess.GuestMeal')),
                ('meal_dish', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.MealDish')),
                ('mess_manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mess.MessManager')),
                ('presence', models.ManyToManyField(blank=True, to='mess.Presence')),
            ],
        ),
        migrations.CreateModel(
            name='StoreKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('half', models.CharField(choices=[('1MO', 'Morning'), ('2EV', 'Evening')], max_length=12, unique_for_date='date')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Boarder', unique_for_date='date')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='store_keeper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.StoreKeeper'),
        ),
    ]
