# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20180206_1858'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureBoarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offdate', models.DateField(blank=True)),
                ('offhalf', models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12)),
                ('ondate', models.DateField(blank=True)),
                ('onhalf', models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal_Date', models.DateField()),
                ('Meal_Half', models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12)),
                ('No_Of_Guest', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal_Dish', models.CharField(blank=True, max_length=100)),
                ('Meal_Date', models.DateField(blank=True)),
                ('Meal_Half', models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='Meal_Date')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('half', models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='meal_date')),
                ('change_by', models.DateTimeField()),
                ('meal_dishes', models.CharField(blank=True, max_length=150)),
                ('has_fish', models.BooleanField(default=False)),
                ('has_chicken', models.BooleanField(default=False)),
                ('has_mutton', models.BooleanField(default=False)),
                ('has_egg', models.BooleanField(default=False)),
                ('extra_meals', models.DecimalField(decimal_places=0, default=4, max_digits=2)),
                ('extra_description', models.TextField(default='')),
                ('adjust_count', models.IntegerField(default=0)),
                ('guest_meal', models.IntegerField(default=0)),
                ('boarder', models.ManyToManyField(blank=True, to='account.Boarder')),
            ],
        ),
        migrations.CreateModel(
            name='StoreKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Date', models.DateField()),
                ('Store_Half', models.CharField(choices=[('1MO', 'Morning'), ('2EV', 'Evening')], max_length=12, unique_for_date='Store_Date')),
                ('Store_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Boarder', unique_for_date='Store_Date')),
            ],
        ),
    ]
