# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='boarder',
            field=models.ManyToManyField(blank=True, null=True, to='account.Boarder'),
        ),
    ]
