# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_auto_20180220_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureboarder',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestmeal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presence',
            name='boarder',
            field=models.ManyToManyField(blank=True, to='account.Boarder'),
        ),
    ]
