# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_auto_20171027_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarder',
            old_name='ispresent',
            new_name='is_present',
        ),
    ]
