# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0007_auto_20171027_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='presence_half',
            field=models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='presence_date'),
        ),
    ]
