# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_auto_20171027_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='presence_half',
            field=models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
    ]
