# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_auto_20171027_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='presence_date',
            field=models.DateField(default=datetime.date(2017, 10, 28)),
        ),
    ]
