# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_boarder_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='dp',
            field=models.ImageField(blank=True, upload_to='images/mess'),
        ),
    ]
