# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0015_auto_20171029_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 29, 6, 40, 4, 482421)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.Boarder'),
        ),
    ]
