# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0018_auto_20171029_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 29, 7, 5, 58, 488608)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.Boarder'),
        ),
    ]
