# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0020_auto_20171031_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 3, 45, 28, 839589)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
