# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0021_auto_20171031_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 5, 54, 32, 933022)),
        ),
    ]
