# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0024_auto_20171031_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 20, 58, 33, 855427)),
        ),
    ]
