# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0028_auto_20171101_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 5, 34, 48, 503861)),
        ),
        migrations.AlterField(
            model_name='temp_chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 5, 34, 48, 503861)),
        ),
    ]
