# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0029_auto_20171101_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_chat',
            name='chat_miliseconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 20, 57, 38, 724153)),
        ),
        migrations.AlterField(
            model_name='temp_chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 20, 57, 38, 724153)),
        ),
    ]
