# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0032_auto_20171101_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 10, 16, 16, 721931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='presence_date',
            field=models.DateField(default=datetime.date(2017, 11, 2)),
        ),
        migrations.AlterField(
            model_name='temp_chat',
            name='chat_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 10, 16, 16, 721931, tzinfo=utc)),
        ),
    ]
