# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0039_auto_20171103_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarder',
            old_name='is_present',
            new_name='presence_evening',
        ),
        migrations.RemoveField(
            model_name='boarder',
            name='presence_half',
        ),
        migrations.AddField(
            model_name='boarder',
            name='presence_morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='futureboarder',
            name='offhalf',
            field=models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
        migrations.AlterField(
            model_name='futureboarder',
            name='onhalf',
            field=models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
    ]
