# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0040_auto_20171104_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarder',
            old_name='presence_evening',
            new_name='is_present',
        ),
        migrations.RemoveField(
            model_name='boarder',
            name='presence_morning',
        ),
        migrations.AddField(
            model_name='boarder',
            name='presence_half',
            field=models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
    ]
