# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0041_auto_20171104_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='presence_half',
            field=models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
    ]
