# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0042_auto_20171104_0518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_Chat',
            new_name='AllChat',
        ),
        migrations.RenameModel(
            old_name='Temp_Chat',
            new_name='TempChat',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='eats_chicken',
            new_name='Eats_Chicken',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='eats_egg',
            new_name='Eats_Egg',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='eats_fish',
            new_name='Eats_Fish',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='eats_mutton',
            new_name='Eats_Mutton',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='is_present',
            new_name='Evening_Presence',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='presence_date',
            new_name='Presence_Date',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='room_number',
            new_name='Room_Number',
        ),
        migrations.RenameField(
            model_name='boarder',
            old_name='year_of_passing',
            new_name='Year_Of_Passing',
        ),
        migrations.RemoveField(
            model_name='boarder',
            name='presence_half',
        ),
        migrations.AddField(
            model_name='boarder',
            name='Morning_Presence',
            field=models.BooleanField(default=True),
        ),
    ]
