# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0043_auto_20171107_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureboarder',
            name='offdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='futureboarder',
            name='offhalf',
            field=models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
        migrations.AlterField(
            model_name='futureboarder',
            name='ondate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='futureboarder',
            name='onhalf',
            field=models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
    ]
