# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0044_auto_20171108_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='allchat',
            name='dp',
            field=models.ImageField(blank=True, upload_to='images/mess'),
        ),
        migrations.AddField(
            model_name='tempchat',
            name='dp',
            field=models.ImageField(blank=True, upload_to='images/mess'),
        ),
    ]
