# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0045_auto_20171109_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allchat',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tempchat',
            name='username',
        ),
        migrations.DeleteModel(
            name='AllChat',
        ),
        migrations.DeleteModel(
            name='TempChat',
        ),
    ]
