# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0047_auto_20171118_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal_Dish', models.DateField(blank=True)),
                ('Meal_Half', models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='meal_date')),
                ('Meal_Date', models.DateField(blank=True)),
            ],
        ),
    ]
