# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0048_meal_dishes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal_Dishes',
            new_name='MealDishes',
        ),
    ]
