# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0049_auto_20171125_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdishes',
            name='Meal_Dish',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
