# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0050_auto_20171125_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdishes',
            name='Meal_Half',
            field=models.CharField(blank=True, choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='Meal_Date'),
        ),
    ]
