# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0051_auto_20171125_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='Presence_Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='dp',
            field=models.ImageField(blank=True, default='images/mess/Screenshot_10.png', upload_to='images/mess'),
        ),
    ]
