# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0052_auto_20171214_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='Presence_Date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
