# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0055_auto_20171218_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal_Date', models.DateField()),
                ('Meal_half', models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='Meal_Date')),
                ('No_Of_Guest', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
