# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0056_guestmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='guest_meal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guestmeal',
            name='No_Of_Guest',
            field=models.IntegerField(default=0),
        ),
    ]
