# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0057_auto_20171219_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestmeal',
            old_name='Meal_half',
            new_name='Meal_Half',
        ),
    ]
