# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0058_auto_20171219_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmeal',
            name='Meal_Half',
            field=models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12),
        ),
    ]
