# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0059_auto_20171219_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.CharField(max_length=50)),
                ('evening', models.CharField(max_length=50)),
                ('store_date', models.DateField()),
                ('store_half', models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='store_date')),
            ],
        ),
    ]
