# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0061_auto_20180105_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storekeeper',
            old_name='morning',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='storekeeper',
            old_name='store_date',
            new_name='Store_Date',
        ),
        migrations.RenameField(
            model_name='storekeeper',
            old_name='store_half',
            new_name='Store_Half',
        ),
        migrations.RemoveField(
            model_name='storekeeper',
            name='evening',
        ),
    ]
