# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0062_auto_20180105_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storekeeper',
            name='Store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Boarder', unique_for_date='Store_Date'),
        ),
        migrations.AlterField(
            model_name='storekeeper',
            name='Store_Half',
            field=models.CharField(choices=[('MO', 'Morning'), ('EV', 'Evening')], max_length=12, unique_for_date='Store_Date'),
        ),
    ]
