# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0063_auto_20180105_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storekeeper',
            old_name='Store',
            new_name='Store_Name',
        ),
    ]
