# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0073_auto_20180106_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storekeeper',
            name='Store_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Boarder', unique_for_date='Store_Date'),
        ),
    ]
