# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0074_auto_20180106_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storekeeper',
            name='Store_Name',
        ),
    ]
