# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171228_1224'),
        ('mess', '0075_remove_storekeeper_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storekeeper',
            name='Store_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Boarder', unique_for_date='Store_Date'),
        ),
    ]
