# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, upload_to='images/Chat')),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
                ('chat_datetime', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='allchat',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tempchat',
            name='username',
        ),
        migrations.DeleteModel(
            name='AllChat',
        ),
        migrations.DeleteModel(
            name='TempChat',
        ),
    ]
