# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171203_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='dp',
            field=models.ImageField(blank=True, upload_to='images/chat'),
        ),
    ]
