# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20171218_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='dp',
            field=models.URLField(blank=True),
        ),
    ]
