# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20171219_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='dp',
            field=models.BinaryField(blank=True),
        ),
    ]
