# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180225_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='dp',
            field=models.TextField(blank=True),
        ),
    ]
