# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('printscan', 'Print & Scan'), ('net', 'Net'), ('library', 'Library'), ('recreation', 'Recreation'), ('canteen', 'Canteen'), ('mess', 'Mess'), ('messbill', 'Mess Bill')], max_length=20)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('added', models.FloatField(default=0.0)),
                ('paid', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True)),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarder', to='account.Boarder')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_by', to='account.Boarder')),
            ],
        ),
    ]
